version: "2"
services:
  app:
    image: "jmaya/mediahub"
    command: "--peer db --peer redis --bind database:postgresql.default --bind redis:redis.default --strategy at-once --channel unstable"
    # volumes:
    #   # - /mnt/MediaHub:/myapp/public/uploads
    #    - ./public/uploads:/myapp/public/uploads
    #    - ./tmp:/myapp/tmp
    #    - ./log:/myapp/log
    # environment:
    #   - PORT=3000
    depends_on:
      - "db"
      - "redis"
    links:
      - "db"
      - "redis"
    ports:
      - "3000:3000"
      - "9631:9631"
    volumes:
      - ./user.toml:/hab/svc/mediahub/user.toml

  db:
    image: "core/postgresql"
    ports:
      - "5432:5432"
    volumes:
      - data_postgresql:/hab/svc/postgresql/data

  redis:
    image: "core/redis"
    ports:
      - "6379"
    volumes:
      - data_redis:/hab/svc/redis/data
volumes:
  data_redis:
  data_postgresql:
