db:
  image: postgres
  ports:
    - "5432"
app:
  # image: mediahub_app
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - /mnt/MediaHub:/myapp/public/uploads
    - /var/log/mediahub:/myapp/log
  ports:
    - "3000"
  links:
    - db
web:
  image: nginx
  ports:
    - "8080:8080"
  volumes:
    - ./conf/container/myapp.conf:/etc/nginx/conf.d/myapp.conf
  volumes_from:
    - app
  links:
    - app
