db:
  image: postgres
  ports:
    - "5432"
  volumes:
    - ./data:/var/lib/postgresql/data
redis:
  image: redis
  ports:
    - "6379"

app:
  #image: jmaya/mediahub_app
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    # - /mnt/MediaHub:/myapp/public/uploads
     - ./public/uploads:/myapp/public/uploads
     - ./tmp:/myapp/tmp
    #- ./:/myapp
     - ./log:/myapp/log
  ports:
    - "3000"
  links:
    - db
    - redis

sidekiq:
  #build: .
  image: mediahub_app
  command: bundle exec sidekiq
  environment:
    - REDIS_URL=redis://redis:6379
  volumes_from:
    - app
  links:
    - db
    - redis

web:
  image: nginx
  ports:
    - "8080:8080"
  volumes:
    - ./config/container/myapp.conf:/etc/nginx/conf.d/myapp.conf
  volumes_from:
    - app
  links:
    - app
