development: &default
  adapter: postgresql
  database: rails_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test: &test
  <<: *default
  database: rails_test

production:
  <<: *default
  database: rails_production


cucumber:
  <<: *test
